monolog:
    handlers:
        exception:
            type:  rotating_file
            path: '%kernel.logs_dir%/exception.%kernel.environment%.log'
            level: debug
            channels: ['exception']
            max_files:  30
    channels:
        - 'exception'
