version: '3'
services:
    php:
        build: ./docker/php
        container_name: tg_bot_nagan_php
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - mysql
#            - rabbitmq

    mysql:
        image: mariadb:10
        container_name: tg_bot_nagan_mysql
        restart: always
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        environment:
            - TZ
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE

    nginx:
        image: nginx:1.17-alpine
        container_name: tg_bot_nagan_nginx
        restart: always
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

#    rabbitmq:
#        image: rafakato/rabbitmq-delayed-message-exchange
#        container_name: tg_bot_nagan_rabbitmq
#        restart: always
#        entrypoint: ['echo', 'RabbitMQ service disabled']
