version: '3.7'
services:
    mysql:
        image: mariadb:10.5
        container_name: naganbot_mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - $MYSQL_EXPOSE_PORT:3306
        environment:
            - MYSQL_DATABASE
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - TZ
        restart: always
volumes:
    mysql:
        name: naganbot_mysql
