monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        exception:
            type:  rotating_file
            path: '%kernel.logs_dir%/exception.%kernel.environment%.log'
            level: debug
            channels: ['exception']
            max_files:  30
    channels:
        - 'exception'
