parameters:
    telegram_route_secret: '%env(TELEGRAM_BOT_TOKEN)%'
    default_locale: ru
    available_locales:
        - ru

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\CommandListener:
        tags:
            - { name: kernel.event_listener, event: boshurik_telegram_bot.update, method: onUpdate, priority: 1 }

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }
        arguments:
            $exceptionLogger: '@monolog.logger.exception'
